language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
# Install dependencies
install: "pip install -r requirements.txt"
script: "cd superlists; py.test; python3 manage.py test functional_tests"
